defmodule LlmScratch.TextUtilsTest do
  use ExUnit.Case

  alias LlmScratch.TextUtils

  test "token_ids_to_text_lossy replaces invalid generated byte tokens" do
    token_ids = Nx.tensor([[6109, 94, 3626]], type: {:s, 64})

    assert TextUtils.token_ids_to_text_lossy(token_ids, "code-davinci-002") ==
             "Every� effort"
  end
end
